import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/Components/Footer";
import { NextUIProvider } from "@nextui-org/react";
import Header from "@/Components/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Sas Corporation Bd",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUIProvider>
          <Header/>
          {children}
          <Footer />
        </NextUIProvider>
      </body>
    </html>
  );
}
